[workspace]
authors   = ["Sam Vente <savente93@proton.me>"]
channels  = ["conda-forge"]
name      = "spec_0_test_package"
platforms = ["linux-64"]
version   = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.9.0"

[feature.foo.dependencies]
scipy  = "*"
xarray = ">=2025.7.1,<2026"

[environments]
bar = ["foo"]
